---
title: "Dash_top"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny 
#shiny é interação 
---
```{r}

```

```{r setup, include=FALSE}
#Dashboard
library(flexdashboard)

#Manipular tabelas 
library(dplyr)

#Gráficos
library(ggplot2)
library(plotly)

# Pgar dados financeiros
library(tidyquant)
```


Column {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput(
  "ticker",
  "Escolha o ticker:", #label
   choices = c("PETR4.SA", "BBAS3.SA", "VALE3.SA", "WEGE3.SA")    #opções
)
```


```{r download}
dados_tbl <- reactive({
  tq_get(input$ticker)
})

```

Column {data-width=500}
-----------------------------------------------------------------------

### Cotações

```{r}

renderDataTable ({
  dados_tbl () %>% 
    select(date, adjusted) %>% 
    arrange(desc(date))
})

```

Column {data-width=500}
-----------------------------------------------------------------------

### Gráficos

```{r}
renderPlotly({
  dados_tbl () %>% 
    ggplot(aes(x = date, y = adjusted)) +
    geom_line()
})

# esse código é o mesmo de cima, mais explicado
# g <- dados_tbl %>% 
#   ggplot(aes(x = date, y = adjusted)) +
#   geom_line()
# 
# ggplotly(g) #para deixar interativo
```

### Gráficos 2

```{r}
renderPlotly({
  tq_get(c("PETR4.SA", "BBAS3.SA", "VALE3.SA", "WEGE3.SA")) %>% 
    group_by(symbol) %>% 
    mutate(cotacao = (adjusted - mean(adjusted))/ sd(adjusted)) %>% 
    ungroup() %>% 
    ggplot(aes(x = date, y = cotacao, color = symbol)) +
    geom_line()
})
```


